name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1.2.0
      - run: zig build -Doptimize=ReleaseSafe
      - uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: ./zig-out/bin/bin
          remote: ~/bin/bin
          host: ${{ secrets.deployHost }}
          port: ${{ secrets.deployPort }}
          user: ${{ secrets.deployUser }}
          key: ${{ secrets.deployKey }}
          pre_upload: "rm ~/bin/bin"
          post_upload: "touch ~/bin/.upgrade_ready"
